config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/register' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'

  get '/dashboard' => 'tasks#dashboard'
  get '/dashboard/:id/taskupdate' => 'tasks#dashboard', as: :taskupdate

  get '/change_stage/:id/:choice_status' => 'tasks#change_stage', :as => :change_stage
  root 'tasks#dashboard'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
	  has_many :tasks
	 has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end





end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/dashboard'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/dashboard'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  # GET /tasks
  # GET /tasks.json


   def change_stage
       @task = Task.find(params[:id])
       @testcoworker = @task.coworker.scan(/\d/).map(&:to_i)
      if  @testcoworker.include? current_user.id or current_user.id == @task.user_id
        @task.update(:tstage => params[:choice_status])
      else
         format.html { redirect_to dashboard_path, notice: 'Only creator and team members can edit the status!' }
      end
   end


  def dashboard
       @tasks = Task.all
       if params[:id].nil?
         @task = Task.new
         @taskform = "Add New Task"
       else
         @task = Task.find(params[:id])
         @taskform = "Edit Task"
       end
  end

  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to dashboard_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|

      if current_user.id == @task.user_id
        if  @task.update(task_params)
          format.html { redirect_to dashboard_path, notice: 'Task was successfully updated.' }
          format.json { render :show, status: :ok, location: @task }
        else
          format.html { render :edit }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      else
          format.html { redirect_to dashboard_path, notice: 'Only creator can edit the title. description, due date, team members and categories.' }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if current_user.id == @task.user_id 

      @task.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: 'Task was successfully destroyed.' }
        format.json { head :no_content }
      end

    else
       redirect_to dashboard_path, notice: 'Only creator can DELETE the task' 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :duedate, :tstage, :user_id, :coworker => [], :tcategories => [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
    end

	 def create
	  user = User.new(user_params)
	  if user.save
	    session[:user_id] = user.id
	    redirect_to '/'
	  else
	    redirect_to '/register'
	  end
	end


	def show
		@user = User.find(params[:id])
		#@tasks = Task.where(:user_id => @user.id)
		@tasks = Task.all.includes(:user)
	end

	def user_params
  	 params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

	<div class="navbar-inner">

	 <span id="mynav">
			<% if current_user %>
			  <span>Signed in as: <b> <%= current_user.name %></b> </span>
			  <%= link_to "Show", controller: "users", action: "show", id: current_user.id %>
			 


			 <%= link_to "Logout", '/logout', :class=>"btn" %>
			<% else %>
			  <%= form_tag '/login', :class=>"navbar-form pull-left" do %>

				  Email: <%= text_field_tag :email %>
				  Password: <%= password_field_tag :password %>
				  <%= submit_tag "Login", :class=>"btn" %>
				  <%= link_to "Register", '/register',
				  :id=>'myregister', :class=>"btn btn-primary" %>

			<% end %>


			<% end %>
	</span>


    </div>


	
	<body>

			<%= yield %>
	
	</body>
	
	
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


 <% if current_user.id == @task.user_id or @task.id.nil? %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "span12" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "span12"  %>
  </div>
  <div class="field">
    <%= f.label :duedate %>
    <%= f.date_field :duedate, :class => "span12" %>
  </div>
  <div class="field">
    <label>Stage</label>
    <%= f.select :tstage, ['to do', 'in progress','completed']%>

  </div>
  <div class="field">
  <label>Task categories</label>
    <% ["design","development","logistics","administration","marketing"].each do |tcategory| %>
    <%= check_box_tag "task[tcategories][]", tcategory, @task.tcategories.include?(tcategory), id: "task_tcategories_#{tcategory}" %> <%= tcategory %><br/>
  <% end %>
  </div>
  <div class="field">
    <%= f.label :coworker %>
   <%= f.select(:coworker, User.where.not(:id=>current_user).collect {|p| [ p.name, p.id ] }, 
                                           { :prompt => "Please select"}, 
                                           { :multiple => true, :size => 5 }) %>
  </div>
  <div class="field">
     <label>Creator:<%= current_user.name if current_user %></label>
    <%= f.hidden_field :user_id, :value => current_user.id if current_user %>
  </div>

    <div class="actions">
    <%= f.submit :class=>"btn btn-large btn-block btn-primary" %>
  </div>
<% end %>


 <% end %>

 <% if current_user.id != @task.user_id && !@task.id.nil?  %>


   <select onchange="choice1(this)" id="changett">
        <option value="<%= @task.tstage %>">Change status </option>
        <option value="to do">to do</option>
        <option value="completed">completed</option>
        <option value="in progress">in progress</option>
    </select>

 <% end %>








<script type="text/javascript">
  
function choice1(select) {

    var choose_stage = select.options[select.selectedIndex].text;
  
     $.ajax({
            type: 'GET',
            url: '/change_stage/<%= @task.id %>/'+choose_stage,
            success: function(content) {
               
            }   
        });location.reload();
        return false; // to stop link
 

}

</script>

 
 

app/views/tasks/_index.html.erb
<div >
<p id="notice" class="alert">Notice: <%= notice %></p>
</div>

<table class="table table-bordered" style="font-size:12px;">
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Duedate</th>
      <th>Stage</th>
      <th>Categories</th>
      <th>Co-workers</th>
      <th>Creator</th>
      <% if current_user %>
      <th colspan="2">Actions</th>
      <% else %>

      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr id="mytaskstyle<%= task.id %>">
        <td><%= task.title %></td>
        <td><%= task.description[0,50] %></td>
        <td><%= task.duedate %></td>
        <td><%= task.tstage %></td>
        <td>
          <% if task.tcategories != "--- []\n"  %>
              <%= task.tcategories %>
          <% else %>
          <% end %>
        </td>
        <td>
           <% if task.coworker != "--- []\n"  %>
                <%= User.where(:id => JSON.parse(task.coworker)).collect {|p| [ p.name] } %>
           <% end %>
        </td>
        <td><%= task.user.name %>
            <%= link_to "Show", controller: "users", action: "show", id: task.user.id %>
        </td>
        <% if current_user %>
        <td><%= link_to 'Update', taskupdate_path(:id =>task),  :class=>"btn btn-success btn-sm" %></td>
        <td><%= link_to 'Destroy', task, method: :delete,:class=>"btn btn-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
        <% else %>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<style type="text/css">
  
  <% if !@task.nil? %>

      #mytaskstyle<%= @task.id %> {

        background-color: #329bff;
        color: white;
        font-size: 13px;
      }
   <% end %>

</style>

app/views/tasks/_new.html.erb
<%= render 'form' %>

app/views/tasks/dashboard.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2" >
      <% if current_user %>
        <legend><%= @taskform %></legend>
        	 <%= render 'new' %>
      <% else %>
          <div class="alert alert-block">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h4>Warning!</h4>
            You don't have permission to create task.
            Please Login or Register.
        </div>
         
      <% end %>
    

    </div>
    <div class="span10" >
      <legend>Task List
        <%= link_to "New task", '/dashboard', :class=>"btn", :id=>"newt" %>
      </legend>
      	  <%= render 'index' %>
    </div>
  </div>
</div>
	  


 
      	 
    

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Duedate</th>
      <th>Tstage</th>
      <th>Tcategory</th>
      <th>Coworker</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.duedate %></td>
        <td><%= task.tstage %></td>
        <td><%= task.tcategory %></td>
        <td><%= task.coworker %></td>
        <td><%= task.creator %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Duedate:</strong>
  <%= @task.duedate %>
</p>

<p>
  <strong>Tstage:</strong>
  <%= @task.tstage %>
</p>

<p>
  <strong>Tcategory:</strong>
  <%= @task.tcategory %>
</p>

<p>
  <strong>Coworker:</strong>
  <%= @task.coworker %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @task.creator %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/new.html.erb
<div class="row-fluid">
  <div class="span4"></div>
  <div class="span4">
  		
		 <legend>Register</legend>


		<%= form_for :user, url: '/users', :class=>"form-horizontal" do |f| %>

		 <div class="control-group">
		    <label class="control-label" for="inputName">Name</label>
		    <div class="controls">
		      <%= f.text_field :name %>
		    </div>
		  </div>
		  <div class="control-group">
		    <label class="control-label" for="inputEmail">Email</label>
		    <div class="controls">
		      <%= f.text_field :email %>
		    </div>
		  </div>

		   <div class="control-group">
		    <label class="control-label" for="inputPassword">Password</label>
		    <div class="controls">
		      <%= f.password_field :password %>
		    </div>
		  </div>

		  <div class="control-group">
		    <label class="control-label" for="inputPassword">Password Confirmation</label>
		    <div class="controls">
		      <%= f.password_field :password_confirmation %>
		    </div>
		  </div>

		  <%= f.submit "RegisterNow", :class=>"btn" %>

		<% end %>

  </div>
  <div class="span4" ></div>
</div>

app/views/users/show.html.erb
<div class="span3" >
      <legend>User Profile</legend>
       <p> Name: <%= @user.name %> </h2>
       <p> Email: <%= @user.email %> </h2>
       <br>
        back to <%= link_to "Dashboard", dashboard_path %>
</div>



<div class="span12" >
      <legend>Task List</legend>
          <%= render '/tasks/index' %>
</div>